### ISSUE TITLE
Rework Navigation with new useCatalog Info

### ISSUE THREAD

**Issue by mvahowe** [Proskomma/diegesis-reboot#31]
# Background
At present, the app gets docSet and document from `useCatalog`. For chapter/verse navigation we need additional information. The current implementation runs a second query to get an array of chapter numbers. This is slow, and also introduces potential race conditions between the navigation components. Adding verse navigation would make this worse.

The latest `useCategory` returns chapter and verse numbers for each document. It should therefore be possible to rework the navigation logic to remove the secondary query. It should also be possible to rewrite all the `navState` whenever each control is changed, ie
- verse changes the verse
- chapter changes the verse and the chapter
- book changes the book and chapter/verse if necessary
- docSet changes docSet, and also book, chapter/verse if necessary

We could probably write a reusable function to implement that logic, which can then be used be all controls.

# Tasks
- [ ] Refactor chapter selection to not require a second query
- [ ] Implement verse selection
- [ ] Add 'jump to docSet/book' option within the Versions accordion

**Comment by mvahowe** [comment]
Note that the latest `useCatalog` hook requires `cv: true` to return this information.
